### ISSUE TITLE
docs: about-this-documentation.md

### ISSUE THREAD

**Issue by iChenLei** [mobxjs/zh.mobx.js.org#12]
1. 请在本issue下回复认领，并提供PR链接(PR用于确认，不需要提供最终PR), PR的标题格式请设为`docs: xx.md`
2. 确认PR有效，本issue将会关闭，对应PR将会标上`翻译中`
3. 认领人在自己的PR上持续commit翻译内容，之后会校对最终合入main分支

> 注：请在未closed的issue列表里寻找感兴趣的翻译任务进行认领，如果发现issue列表里不存在且PR列表也没有翻译某个文档，请提issue并@iChenLei告知，非常感谢。

**Comment by iChenLei** [comment]
翻译链接 https://github.com/mobxjs/zh.mobx.js.org/edit/main/docs/about-this-documentation.md

**Comment by BlackHole1** [comment]
我来翻译吧

**Comment by iChenLei** [comment]
好的 你回复里写上对应PR即可 这是一个例子issue 我现在有点忙，晚点把所有文档列在issue列表里。谢谢

**Comment by BlackHole1** [comment]
https://github.com/mobxjs/zh.mobx.js.org/pull/13

**Comment by BlackHole1** [comment]
> 好的 你回复里写上对应PR即可 这是一个例子issue 我现在有点忙，晚点把所有文档列在issue列表里。谢谢

我个人理解，应该是需要有人先认领，进行回复，然后再进行翻译 -> 提交PR

而不是： 翻译 -> 提交PR -> 评论此 issue

因为可能在翻译的过程中，其他人在不知情的情况下进行翻译，那么当翻译好后，会发现已经有人翻译好了。

**Comment by iChenLei** [comment]
嗯，感谢你的回复。流程是 1.回复 -> 2.提PR(确认有效，打Label，关issue) -> 3.认领人持续翻译
提PR ≠  最终PR，杜绝不知情情况下暗自翻译
