### ISSUE TITLE
docs: intercept-and-observe.md

### ISSUE THREAD

**Issue by iChenLei** [mobxjs/zh.mobx.js.org#24]
1. 请在本issue下回复认领，并提供PR链接(PR用于确认，不需要提供最终翻译完成的PR), PR的标题格式请设为`docs: xx.md`
2. 确认PR有效，本issue将会关闭，对应PR将会标上`翻译中`Label
3. 认领人在自己的PR上持续commit翻译内容，之后会进行校对，最终合入main分支

> 注：请在未Closed的issue列表里寻找感兴趣的翻译任务进行认领，如果发现issue列表里不存在且PR列表也没有翻译某个文档，请提issue并@iChenLei告知有翻译遗漏，非常感谢。认领流程可参考 [#12](https://github.com/mobxjs/zh.mobx.js.org/issues/12)

**Comment by iChenLei** [comment]
翻译链接 https://github.com/mobxjs/zh.mobx.js.org/edit/main/docs/intercept-and-observe.md
文档网址 https://zh.mobx.js.org/intercept-and-observe.html

**Comment by Cyberhan123** [comment]
这个交给我吧

**Comment by standout-jjc** [comment]
> 这个交给我吧

并提供PR链接

**Comment by iChenLei** [comment]
@Cyberhan123 感谢你的参与，认领流程可以可以参考 https://github.com/mobxjs/zh.mobx.js.org/issues/12 提供一个有效的PR即可，提翻译PR可以直接在Github上操作，而且建议翻译也在网页上进行减轻各位译者的负担。:heart:

**Comment by Cyberhan123** [comment]
好的，我先提一个未完成的pr占位稍后会补充完整
https://github.com/mobxjs/zh.mobx.js.org/pull/58
