### ISSUE TITLE
docs: react-optimizations.md

### ISSUE THREAD

**Issue by iChenLei** [mobxjs/zh.mobx.js.org#30]
1. 请在本issue下回复认领，并提供PR链接(PR用于确认，不需要提供最终翻译完成的PR), PR的标题格式请设为`docs: xx.md`
2. 确认PR有效，本issue将会关闭，对应PR将会标上`翻译中`Label
3. 认领人在自己的PR上持续commit翻译内容，之后会进行校对，最终合入main分支

> 注：请在未Closed的issue列表里寻找感兴趣的翻译任务进行认领，如果发现issue列表里不存在且PR列表也没有翻译某个文档，请提issue并@iChenLei告知有翻译遗漏，非常感谢。认领流程可参考 [#12](https://github.com/mobxjs/zh.mobx.js.org/issues/12)

**Comment by iChenLei** [comment]
翻译链接 https://github.com/mobxjs/zh.mobx.js.org/edit/main/docs/react-optimizations.md
文档网址 https://zh.mobx.js.org/react-optimizations.html

**Comment by berber1016** [comment]
认领: #44
